onlyBuiltDependencies:
  - '@mongodb-js/zstd'
  - '@tailwindcss/oxide'
  - cpu-features
  - esbuild
  - get-console-process-list
  - glibc-version
  - kerberos
  - mongodb-client-encryption
  - mongodb-crypt-library-version
  - native-machine-id
  - os-dns-native
  - ssh2
  - win-export-certificate-and-key
